gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("images.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

images/urls.py
from django.urls import path
from images import views

app_name = "images"

urlpatterns = [
    path("", views.home, name="home"),
    path('add_image/', views.add_image, name="add_image"),
    path('update_image/<str:id_image>/', views.update_image, name="update_image"),
    path('detele_image/<str:id_image>/', views.delete_image, name="delete_image"),
    path('api/', views.image_list_rest, name="image_list_rest"),
    path('json_file/', views.image_list_json_file, name="image_list_json_file"),
]

images/models.py
from django.db import models


class Album(models.Model):
    album_id = models.AutoField(primary_key=True)

    def __str__(self):
        return f"Album nr. {self.album_id}"


class Image(models.Model):
    title = models.CharField(max_length=200)
    albumId = models.CharField(max_length=5, blank=True, null=True)
    width = models.CharField(max_length=20)
    height = models.CharField(max_length=20)
    color = models.CharField(max_length=20)
    image = models.FileField(upload_to='content', null=True, blank=True)
    url = models.URLField(null=True)

images/forms.py
from django import forms
from images.models import Image, Album


class AddImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['title', 'albumId', 'image', 'url']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'albumId': forms.TextInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'url': forms.TextInput(attrs={'class': 'form-control'}),
        }


class UpdateImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['title', 'albumId', 'image']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'albumId': forms.TextInput(attrs={'class': 'form-control'}),
        }

images/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import JsonResponse
from django.core.files.base import ContentFile
from django.core.paginator import Paginator

from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status


from images.models import Image
from images.forms import AddImageForm, UpdateImageForm
from images.serializers import ImageSerializer

from PIL import Image as ImageSize
from colorthief import ColorThief

import requests
import ast


def home(request):
    images = Image.objects.all().order_by('-id')

    #Set up Pagination
    p = Paginator(images, 20)
    page = request.GET.get('page')
    images_p = p.get_page(page)

    context = {'images': images, 'images_p': images_p}
    return render(request, "images/index.html", context)


def add_image(request):
    if request.method == "POST":
        data = request.POST
        image_url = data['url']
        image_name = image_url.split("/")[-1]
        response = requests.get(image_url)
        obj = Image()
        obj.image.save(image_name, ContentFile(response.content), save=False)

        image_size = ImageSize.open(obj.image)
        ct = ColorThief(obj.image)
        dominant_color = ct.get_color(quality=1)

        obj.title = data['title']
        obj.albumId = data['albumId']
        obj.width = image_size.size[0],
        obj.height = image_size.size[1],
        obj.color = dominant_color,
        obj.save()
    form = AddImageForm()

    context = {'form': form}
    return render(request, "images/forms/add_image.html", context)


def delete_image(request, id_image):
    image = Image.objects.get(pk=id_image)
    image.delete()
    messages.success(request, "The photo has been correctly added")
    return redirect('images:home')


def update_image(request, id_image):
    image = Image.objects.get(pk=id_image)
    if request.method == "POST":
        form = UpdateImageForm(request.POST, request.FILES, instance=image)
        if form.is_valid():
            form.save()
            messages.success(request, "The photo has been correctly updated")
    form = UpdateImageForm(instance=image)

    context = {'form': form}
    return render(request, "images/forms/edit_image.html", context)


@api_view(['GET', 'POST'])
def image_list_rest(request):
    if request.method == "GET":
        images = Image.objects.all()
        serializer = ImageSerializer(images, many=True)
        return JsonResponse(serializer.data, safe=False)

    if request.method == "POST":
        data = request.data
        for n in range(len(data)):
            image_url = data[n]['url']
            image_name = image_url.split("/")[-1]
            response = requests.get(image_url + ".jpg")
            obj = Image()
            obj.image.save(image_name, ContentFile(response.content), save=False)

            image_size = ImageSize.open(obj.image)
            ct = ColorThief(obj.image)
            dominant_color = ct.get_color(quality=1)

            obj.title = data[n]['title']
            obj.albumId = data[n]['albumId']
            obj.width = image_size.size[0],
            obj.height = image_size.size[1],
            obj.color = dominant_color,
            obj.save()

        return Response(status=status.HTTP_201_CREATED)


def image_list_json_file(request):
    with open("static/photos.txt") as f:
        files = ast.literal_eval(f.read())

    for index in range(len(files)):
        for key in files[index]:
            print(files[index][key])

        image_url = files[index]['url']
        image_name = image_url.split("/")[-1]
        response = requests.get(image_url + ".jpg")
        obj = Image()
        obj.image.save(image_name, ContentFile(response.content), save=False)

        image_size = ImageSize.open(obj.image)
        ct = ColorThief(obj.image)
        dominant_color = ct.get_color(quality=1)

        obj.title = files[index]['title']
        obj.albumId = files[index]['albumId']
        obj.width = image_size.size[0],
        obj.height = image_size.size[1],
        obj.color = dominant_color,
        obj.save()

    context = {}
    return render(request, "images/index.html", context)

templates/images/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
  <!-- MDB -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.css" rel="stylesheet"/>

  <title>Title</title>
</head>
<body>
{% include 'images/includes/navbar.html' %}
{% include 'images/includes/messages.html' %}


{% block content %}
{% endblock %}

{% include 'images/includes/footer.html' %}
<!-- MDB -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.js"></script>
</body>
</html>

templates/images/forms/add_image.html
{% extends 'images/base.html' %}
{% block content %}

<div class="container">
    <div class="row">
            <h1 class="mt-3">Add Image</h1>
        <div class="col-lg-12 my-5">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Add image</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/images/forms/edit_image.html
{% extends 'images/base.html' %}
{% block content %}

<div class="container">
    <div class="row">
            <h1 class="mt-3">Update Image</h1>
        <div class="col-lg-12 my-5">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Update image</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/images/includes/footer.html
<footer class="bg-light text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-dark" href="https://dmachala.it/">Dawid Machała</a>
  </div>
  <!-- Copyright -->
</footer>

templates/images/includes/messages.html
{% if messages %}
  {% for message in messages %}
  <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    {{ message }}
  </div>
  {% endfor %}
{% endif %}

templates/images/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'images:home' %}">Gallery</a>
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'images:home' %}">Home</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/images/index.html
{% extends 'images/base.html' %}
{% block content %}
<div class="container">
    <div class="row my-3">
        <div class="col-md-12">
            <h1>List images</h1>
            <div class="col-md-12 text-end">
                <button type="button" class="btn btn-primary" onclick="location.href='{% url 'images:add_image' %}'">Add Image</button>
            </div>
            <table class="table  text-center">
              <thead>
                <tr>
                  <th scope="col">ID</th>
                  <th scope="col">Title</th>
                  <th scope="col">Album</th>
                  <th scope="col">Width</th>
                  <th scope="col">Height</th>
                  <th scope="col">Color</th>
                  <th scope="col">URL</th>
                  <th scope="col">Action</th>
                </tr>
              </thead>
              <tbody>
              {% for image in images_p %}
                <tr>
                  <th scope="row">{{ image.id }}</th>
                  <td>{{ image.title }}</td>
                  <td>{{ image.albumId }}</td>
                  <td>{{ image.width }}</td>
                  <td>{{ image.height }}</td>
                  <td>{{ image.color }}</td>
                  <td>{{ image.image }}</td>
                  <td>
                      <a href="{% url 'images:update_image' image.id %}">Update</a>
                      <a href="{% url 'images:delete_image' image.id %}">Delete</a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        </div>


        <div class="row mt-3">
            <nav aria-label="...">
              <ul class="pagination text-center justify-content-center align-content-center">
                {% if images_p.has_previous %}
                    <li class="page-item">
                      <a href="?page=1" class="page-link">&laquo; First</a>
                    </li>
                    <li class="page-item">
                      <a href="?page={{ images_p.previous_page_number }}" class="page-link">Previous</a>
                    </li>
                {% endif %}

                <li class="page-item"><a class="page-link" href="#">Page {{ images_p.number }} of {{ images_p.paginator.num_pages }}</a></li>

                {% if images_p.has_next %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{ images_p.next_page_number }}">Next</a>
                    </li>
                    <li class="page-item">
                      <a class="page-link" href="?page={{ images_p.paginator.num_pages }}">Last &raquo;</a>
                    </li>
                {% endif %}
              </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}